server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54323/enrollment_db
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/amatum

  grpc:
    server:
      enabled: true
      port: 9093
    client:
      course-service:
        address: localhost
        port: 9092

keycloak:
  clients:
    lumina-client-id: lms-ui
    opus-client-id: opus-ui

gotenberg:
  url: http://localhost:3000
