spring:
  application:
    name: enrollment-service

  profiles:
    active: dev

  threads:
    virtual:
      enabled: true

logging:
  level:
    root: info

app:
  domain:
    quiz-attempt:
      passmark: 50


