spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/identity_db
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URI}

keycloak:
  realm: amatum
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  backend-client-id: ${KEYCLOAK_IDENTITY_CLIENT_ID}
  backend-client-secret: ${KEYCLOAK_IDENTITY_CLIENT_SECRET}
  clients:
    lumina-client-id: lms-ui
    opus-client-id: opus-ui
  groups:
    learner-id: ${KEYCLOAK_LEARNER_GROUP_ID}
    manager-id: ${KEYCLOAK_MANAGER_GROUP_ID}