spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URI}

  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_APIKEY}
      chat:
        model: gpt-5.6-sol

    vectorstore:
      qdrant:
        initialize-schema: true
        host: qdrant
        port: 6334
        collection-name: amatum
        api-key: ${QDRANT_API_KEY}

keycloak:
  clients:
    lumina-client-id: lms-ui
    opus-client-id: opus-ui

logging:
  level:
    root: info

firecrawl:
  api-key: {FIRECRAWL_API_KEY}
  search:
    max-results: 5