spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URI}

  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_APIKEY}
      chat:
        model: gpt-5.6-luna


keycloak:
  clients:
    lumina-client-id: lms-ui
    opus-client-id: opus-ui

logging:
  level:
    root: info