server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URI}

#  ai:
#    model:
#      chat: ollama
#    ollama:
#      base-url: http://localhost:11435
#      chat:
#        model: mistral
#        temperature: 0.0
#      init:
#        pull-model-strategy: when_missing

  ai:
    model:
      chat: openai
    openai:
      api-key: ${OPENAI_APIKEY}
      chat:
        model: gpt-5.6-sol

    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: amatum

keycloak:
  clients:
    lumina-client-id: lms-ui
    opus-client-id: opus-ui

logbook:
  format:
    style: http

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.ai: DEBUG
    org.zalando.logbook: TRACE